-- CFO CoWork Demo — 99 teardown
-- Removes everything created by this demo. Irreversible.
DROP AGENT IF EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS.ALDWYCH_CFO_AGENT;
DROP DATABASE IF EXISTS CFO_DEMO;
DROP WAREHOUSE IF EXISTS CFO_DEMO_WH;
